In [1]:
import numpy as pd
import pandas as pd

In [7]:
import pandas as pd

df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1, 1, 0, 0]
})

print(df)

                    text  output
0   people watch campusx       1
1          campusx watch       1
2   people write comment       0
3  campusx write comment       0

In [8]:
df

                    text  output
0   people watch campusx       1
1          campusx watch       1
2   people write comment       0
3  campusx write comment       0

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [12]:
bow = cv.fit_transform(df['text'])

In [13]:
# Vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [14]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[1 0 0 1 0]]

In [15]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "I love Python",
    "I love Java",
    "Python is easy"
]

cv = CountVectorizer()

X = cv.fit_transform(corpus)

print(cv.get_feature_names_out())
print(X.toarray())

['easy' 'is' 'java' 'love' 'python']
[[0 0 0 1 1]
 [0 0 1 1 0]
 [1 1 0 0 1]]

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(2, 2))

X = cv.fit_transform(["I love Python programming"])

print(cv.get_feature_names_out())

['love python' 'python programming']

In [18]:
df

                    text  output
0   people watch campusx       1
1          campusx watch       1
2   people write comment       0
3  campusx write comment       0

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['text']).toarray()

print(X)

[[0.49681612 0.         0.61366674 0.61366674 0.        ]
 [0.62922751 0.         0.         0.77722116 0.        ]
 [0.         0.57735027 0.57735027 0.         0.57735027]
 [0.49681612 0.61366674 0.         0.         0.61366674]]

In [22]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']